export const WS_EVENTS = {
  RUN_QUEUED: "RUN_QUEUED",
  RUN_STARTED: "RUN_STARTED",
  RUN_COMPLETED: "RUN_COMPLETED",
  RUN_FAILED: "RUN_FAILED",
  NODE_STARTED: "NODE_STARTED",
  NODE_COMPLETED: "NODE_COMPLETED",
  AGENT_MESSAGE_CREATED: "AGENT_MESSAGE_CREATED",
  TOOL_CALL_STARTED: "TOOL_CALL_STARTED",
  TOOL_CALL_COMPLETED: "TOOL_CALL_COMPLETED",
  TOOL_CALL_FAILED: "TOOL_CALL_FAILED",
  CONDITION_EVALUATED: "CONDITION_EVALUATED",
  TOKEN_USAGE_RECORDED: "TOKEN_USAGE_RECORDED",
} as const;
