from enum import StrEnum
from app.core.messages import ResponseMessage


class NodeType(StrEnum):
    START = "START"
    AGENT = "AGENT"
    TOOL = "TOOL"
    CONDITION = "CONDITION"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    END = "END"


class RunStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class EdgeCondition(StrEnum):
    ALWAYS = "always"
    APPROVED = "approved"
    REJECTED = "rejected"
    RESOLVED = "resolved"
    ESCALATE = "escalate"


class WebSocketEventType(StrEnum):
    RUN_STARTED = "RUN_STARTED"
    RUN_COMPLETED = "RUN_COMPLETED"
    RUN_FAILED = "RUN_FAILED"
    NODE_STARTED = "NODE_STARTED"
    NODE_COMPLETED = "NODE_COMPLETED"
    AGENT_MESSAGE_CREATED = "AGENT_MESSAGE_CREATED"
    TOOL_CALL_STARTED = "TOOL_CALL_STARTED"
    TOOL_CALL_COMPLETED = "TOOL_CALL_COMPLETED"
    TOOL_CALL_FAILED = "TOOL_CALL_FAILED"
    CONDITION_EVALUATED = "CONDITION_EVALUATED"
    TOKEN_USAGE_RECORDED = "TOKEN_USAGE_RECORDED"


class ErrorCode(StrEnum):
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    WORKFLOW_NOT_FOUND = "WORKFLOW_NOT_FOUND"
    AGENT_NOT_FOUND = "AGENT_NOT_FOUND"
    RUN_NOT_FOUND = "RUN_NOT_FOUND"
    TOOL_NOT_FOUND = "TOOL_NOT_FOUND"
    LLM_ERROR = "LLM_ERROR"
