from enum import StrEnum
from app.core.messages import ResponseMessage


class NodeType(StrEnum):
    START = "START"
    AGENT = "AGENT"
    TOOL = "TOOL"
    CONDITION = "CONDITION"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    END = "END"


class RunStatus(StrEnum):
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    WAITING_INPUT = "WAITING_INPUT"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class NodeRunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    RETRYING = "RETRYING"
    CANCELLED = "CANCELLED"


class EdgeCondition(StrEnum):
    ALWAYS = "always"
    APPROVED = "approved"
    REJECTED = "rejected"
    RESOLVED = "resolved"
    ESCALATE = "escalate"
    EXPRESSION = "expression"


class WebSocketEventType(StrEnum):
    RUN_STARTED = "RUN_STARTED"
    RUN_COMPLETED = "RUN_COMPLETED"
    RUN_FAILED = "RUN_FAILED"
    RUN_CANCELLED = "RUN_CANCELLED"
    RUN_LOG = "RUN_LOG"
    NODE_STARTED = "NODE_STARTED"
    NODE_COMPLETED = "NODE_COMPLETED"
    NODE_FAILED = "NODE_FAILED"
    NODE_SKIPPED = "NODE_SKIPPED"
    AGENT_MESSAGE_CREATED = "AGENT_MESSAGE_CREATED"
    LLM_TOOL_CALL_REQUESTED = "LLM_TOOL_CALL_REQUESTED"
    TOOL_CALL_STARTED = "TOOL_CALL_STARTED"
    TOOL_CALL_COMPLETED = "TOOL_CALL_COMPLETED"
    TOOL_CALL_FAILED = "TOOL_CALL_FAILED"
    CONDITION_EVALUATED = "CONDITION_EVALUATED"
    TOKEN_USAGE_RECORDED = "TOKEN_USAGE_RECORDED"
    GUARDRAIL_VIOLATION = "GUARDRAIL_VIOLATION"


class ErrorCode(StrEnum):
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    WORKFLOW_NOT_FOUND = "WORKFLOW_NOT_FOUND"
    AGENT_NOT_FOUND = "AGENT_NOT_FOUND"
    RUN_NOT_FOUND = "RUN_NOT_FOUND"
    TOOL_NOT_FOUND = "TOOL_NOT_FOUND"
    LLM_ERROR = "LLM_ERROR"
    GUARDRAIL_VIOLATION = "GUARDRAIL_VIOLATION"
